// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARRXvxIGw1ncrqLM0ExKYEWVsUq20IfRo',
    appId: '1:120234879800:web:8756d50d22e2d2cd00efcd',
    messagingSenderId: '120234879800',
    projectId: 'sched-ease',
    authDomain: 'sched-ease.firebaseapp.com',
    storageBucket: 'sched-ease.appspot.com',
    measurementId: 'G-6W55EEVGRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYneIoCXu4b5Sixg140cbtr5LK1O7_zGc',
    appId: '1:120234879800:android:1131a79d6fe3548400efcd',
    messagingSenderId: '120234879800',
    projectId: 'sched-ease',
    storageBucket: 'sched-ease.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyjhOhSe0h2_g0nV-I90l9DTI-6TAXGrw',
    appId: '1:120234879800:ios:dd485422c7cf8f1b00efcd',
    messagingSenderId: '120234879800',
    projectId: 'sched-ease',
    storageBucket: 'sched-ease.appspot.com',
    iosClientId: '120234879800-8p3lbruvijcjirmi0mkqm05lp7sac3kd.apps.googleusercontent.com',
    iosBundleId: 'io.github.amansikarwar.schedease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyjhOhSe0h2_g0nV-I90l9DTI-6TAXGrw',
    appId: '1:120234879800:ios:dd485422c7cf8f1b00efcd',
    messagingSenderId: '120234879800',
    projectId: 'sched-ease',
    storageBucket: 'sched-ease.appspot.com',
    iosClientId: '120234879800-8p3lbruvijcjirmi0mkqm05lp7sac3kd.apps.googleusercontent.com',
    iosBundleId: 'io.github.amansikarwar.schedease',
  );
}
